name: Rust

on:
  pull_request:
    branches: [ "release" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Nightly version
      run: rustup install nightly
    - name: Set nightly as default
      run: rustup default nightly
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: port-scanner-${{ matrix.os }}
        path: target/release
